services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: routerdb
    ports:
      - "5432:5432"
    networks:
      - router-net

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - router-net

  grafana:
    image: grafana/grafana:10.4.5
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - router-net

  router:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/routerdb
      - API_KEY=dev-key
    depends_on: [db]
    ports:
      - "8000:8000"
    networks:
      - router-net
  


networks:
  router-net:
    driver: bridge
    
volumes:
  grafana-storage:
    driver: local
